### ISSUE TITLE
不兼容华为8.1.0 以上的手机，这个该怎么解决

### ISSUE THREAD

**Issue by bingely** [the-pig-of-jungle/SmartShow#5]
java.lang.ClassCastException: android.graphics.drawable.GradientDrawable cannot be cast to android.graphics.drawable.NinePatchDrawable
	at com.coder.zzq.smartshow.toast.SmartToast.setupPlainToast(SmartToast.java:118)
	at com.coder.zzq.smartshow.toast.SmartToast.getToast(SmartToast.java:87)
	at com.coder.zzq.smartshow.toast.SmartToast.showInCenter(SmartToast.java:160)
	at com.charlie.halffourcourse.base.BaseActivity.showToast(BaseActivity.java:87)

**Comment by the-pig-of-jungle** [comment]
已解决。使用1.0.4以上版本
